// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yidbijzsfrwqskjzawqq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlpZGJpanpzZnJ3cXNranphd3FxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA3MjkyNTAsImV4cCI6MjA3NjMwNTI1MH0.8Q_wm2Z37GafNi9yFOu845PrxgtdJnMT7nQHDchdyU4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});